package cn.edu.hbpu.trip.pojo;

import java.util.Date;

public class Contentinfo {
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    private User user;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contentinfo.contentid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer contentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contentinfo.secondid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer secondid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contentinfo.goodsid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contentinfo.uid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contentinfo.overtime
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Date overtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contentinfo.userword
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String userword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contentinfo.contentid
     *
     * @return the value of contentinfo.contentid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getContentid() {
        return contentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contentinfo.contentid
     *
     * @param contentid the value for contentinfo.contentid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setContentid(Integer contentid) {
        this.contentid = contentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contentinfo.secondid
     *
     * @return the value of contentinfo.secondid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getSecondid() {
        return secondid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contentinfo.secondid
     *
     * @param secondid the value for contentinfo.secondid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setSecondid(Integer secondid) {
        this.secondid = secondid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contentinfo.goodsid
     *
     * @return the value of contentinfo.goodsid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contentinfo.goodsid
     *
     * @param goodsid the value for contentinfo.goodsid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contentinfo.uid
     *
     * @return the value of contentinfo.uid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contentinfo.uid
     *
     * @param uid the value for contentinfo.uid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contentinfo.overtime
     *
     * @return the value of contentinfo.overtime
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Date getOvertime() {
        return overtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contentinfo.overtime
     *
     * @param overtime the value for contentinfo.overtime
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setOvertime(Date overtime) {
        this.overtime = overtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contentinfo.userword
     *
     * @return the value of contentinfo.userword
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getUserword() {
        return userword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contentinfo.userword
     *
     * @param userword the value for contentinfo.userword
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setUserword(String userword) {
        this.userword = userword == null ? null : userword.trim();
    }
}