package cn.edu.hbpu.trip.pojo;

import java.util.ArrayList;
import java.util.List;

public class GlinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public GlinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGlidIsNull() {
            addCriterion("glid is null");
            return (Criteria) this;
        }

        public Criteria andGlidIsNotNull() {
            addCriterion("glid is not null");
            return (Criteria) this;
        }

        public Criteria andGlidEqualTo(Integer value) {
            addCriterion("glid =", value, "glid");
            return (Criteria) this;
        }

        public Criteria andGlidNotEqualTo(Integer value) {
            addCriterion("glid <>", value, "glid");
            return (Criteria) this;
        }

        public Criteria andGlidGreaterThan(Integer value) {
            addCriterion("glid >", value, "glid");
            return (Criteria) this;
        }

        public Criteria andGlidGreaterThanOrEqualTo(Integer value) {
            addCriterion("glid >=", value, "glid");
            return (Criteria) this;
        }

        public Criteria andGlidLessThan(Integer value) {
            addCriterion("glid <", value, "glid");
            return (Criteria) this;
        }

        public Criteria andGlidLessThanOrEqualTo(Integer value) {
            addCriterion("glid <=", value, "glid");
            return (Criteria) this;
        }

        public Criteria andGlidIn(List<Integer> values) {
            addCriterion("glid in", values, "glid");
            return (Criteria) this;
        }

        public Criteria andGlidNotIn(List<Integer> values) {
            addCriterion("glid not in", values, "glid");
            return (Criteria) this;
        }

        public Criteria andGlidBetween(Integer value1, Integer value2) {
            addCriterion("glid between", value1, value2, "glid");
            return (Criteria) this;
        }

        public Criteria andGlidNotBetween(Integer value1, Integer value2) {
            addCriterion("glid not between", value1, value2, "glid");
            return (Criteria) this;
        }

        public Criteria andHeadidIsNull() {
            addCriterion("headid is null");
            return (Criteria) this;
        }

        public Criteria andHeadidIsNotNull() {
            addCriterion("headid is not null");
            return (Criteria) this;
        }

        public Criteria andHeadidEqualTo(Integer value) {
            addCriterion("headid =", value, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidNotEqualTo(Integer value) {
            addCriterion("headid <>", value, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidGreaterThan(Integer value) {
            addCriterion("headid >", value, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidGreaterThanOrEqualTo(Integer value) {
            addCriterion("headid >=", value, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidLessThan(Integer value) {
            addCriterion("headid <", value, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidLessThanOrEqualTo(Integer value) {
            addCriterion("headid <=", value, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidIn(List<Integer> values) {
            addCriterion("headid in", values, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidNotIn(List<Integer> values) {
            addCriterion("headid not in", values, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidBetween(Integer value1, Integer value2) {
            addCriterion("headid between", value1, value2, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidNotBetween(Integer value1, Integer value2) {
            addCriterion("headid not between", value1, value2, "headid");
            return (Criteria) this;
        }

        public Criteria andIslikeIsNull() {
            addCriterion("islike is null");
            return (Criteria) this;
        }

        public Criteria andIslikeIsNotNull() {
            addCriterion("islike is not null");
            return (Criteria) this;
        }

        public Criteria andIslikeEqualTo(Integer value) {
            addCriterion("islike =", value, "islike");
            return (Criteria) this;
        }

        public Criteria andIslikeNotEqualTo(Integer value) {
            addCriterion("islike <>", value, "islike");
            return (Criteria) this;
        }

        public Criteria andIslikeGreaterThan(Integer value) {
            addCriterion("islike >", value, "islike");
            return (Criteria) this;
        }

        public Criteria andIslikeGreaterThanOrEqualTo(Integer value) {
            addCriterion("islike >=", value, "islike");
            return (Criteria) this;
        }

        public Criteria andIslikeLessThan(Integer value) {
            addCriterion("islike <", value, "islike");
            return (Criteria) this;
        }

        public Criteria andIslikeLessThanOrEqualTo(Integer value) {
            addCriterion("islike <=", value, "islike");
            return (Criteria) this;
        }

        public Criteria andIslikeIn(List<Integer> values) {
            addCriterion("islike in", values, "islike");
            return (Criteria) this;
        }

        public Criteria andIslikeNotIn(List<Integer> values) {
            addCriterion("islike not in", values, "islike");
            return (Criteria) this;
        }

        public Criteria andIslikeBetween(Integer value1, Integer value2) {
            addCriterion("islike between", value1, value2, "islike");
            return (Criteria) this;
        }

        public Criteria andIslikeNotBetween(Integer value1, Integer value2) {
            addCriterion("islike not between", value1, value2, "islike");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table glinfo
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}