package cn.edu.hbpu.trip.pojo;

import java.util.List;

public class Goodsinfo {

    private int stateid;
    public List<Picinfo> getPicList() {
        return picList;
    }

    public void setPicList(List<Picinfo> picList) {
        this.picList = picList;
    }
    private List<Integer> shoppingList;
    private List<Picinfo> picList;
    private List<Contentinfo> pingLunList;

    public List<Contentinfo> getPingLunList() {
        return pingLunList;
    }

    public void setPingLunList(List<Contentinfo> pingLunList) {
        this.pingLunList = pingLunList;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.goodsid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.adviceid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer adviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.title
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.firstpic
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String firstpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.price
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.num
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.appraise
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Float appraise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.route
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String route;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.clubinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String clubinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.clubtel
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String clubtel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.clubtitle
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String clubtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.ctx
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String ctx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.goodsid
     *
     * @return the value of goodsinfo.goodsid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.goodsid
     *
     * @param goodsid the value for goodsinfo.goodsid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.adviceid
     *
     * @return the value of goodsinfo.adviceid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getAdviceid() {
        return adviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.adviceid
     *
     * @param adviceid the value for goodsinfo.adviceid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setAdviceid(Integer adviceid) {
        this.adviceid = adviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.title
     *
     * @return the value of goodsinfo.title
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.title
     *
     * @param title the value for goodsinfo.title
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.firstpic
     *
     * @return the value of goodsinfo.firstpic
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getFirstpic() {
        return firstpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.firstpic
     *
     * @param firstpic the value for goodsinfo.firstpic
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setFirstpic(String firstpic) {
        this.firstpic = firstpic == null ? null : firstpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.price
     *
     * @return the value of goodsinfo.price
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.price
     *
     * @param price the value for goodsinfo.price
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.num
     *
     * @return the value of goodsinfo.num
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.num
     *
     * @param num the value for goodsinfo.num
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.appraise
     *
     * @return the value of goodsinfo.appraise
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Float getAppraise() {
        return appraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.appraise
     *
     * @param appraise the value for goodsinfo.appraise
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setAppraise(Float appraise) {
        this.appraise = appraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.route
     *
     * @return the value of goodsinfo.route
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getRoute() {
        return route;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.route
     *
     * @param route the value for goodsinfo.route
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setRoute(String route) {
        this.route = route == null ? null : route.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.clubinfo
     *
     * @return the value of goodsinfo.clubinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getClubinfo() {
        return clubinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.clubinfo
     *
     * @param clubinfo the value for goodsinfo.clubinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setClubinfo(String clubinfo) {
        this.clubinfo = clubinfo == null ? null : clubinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.clubtel
     *
     * @return the value of goodsinfo.clubtel
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getClubtel() {
        return clubtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.clubtel
     *
     * @param clubtel the value for goodsinfo.clubtel
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setClubtel(String clubtel) {
        this.clubtel = clubtel == null ? null : clubtel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.clubtitle
     *
     * @return the value of goodsinfo.clubtitle
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getClubtitle() {
        return clubtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.clubtitle
     *
     * @param clubtitle the value for goodsinfo.clubtitle
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setClubtitle(String clubtitle) {
        this.clubtitle = clubtitle == null ? null : clubtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.ctx
     *
     * @return the value of goodsinfo.ctx
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getCtx() {
        return ctx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.ctx
     *
     * @param ctx the value for goodsinfo.ctx
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setCtx(String ctx) {
        this.ctx = ctx == null ? null : ctx.trim();
    }

    public List<Integer> getShoppingList() {
        return shoppingList;
    }

    public void setShoppingList(List<Integer> shoppingList) {
        this.shoppingList = shoppingList;
    }

    public int getStateid() {
        return stateid;
    }

    public void setStateid(int stateid) {
        this.stateid = stateid;
    }
}