package cn.edu.hbpu.trip.pojo;

import java.util.ArrayList;
import java.util.List;

public class HeadtpinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public HeadtpinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTpidIsNull() {
            addCriterion("tpid is null");
            return (Criteria) this;
        }

        public Criteria andTpidIsNotNull() {
            addCriterion("tpid is not null");
            return (Criteria) this;
        }

        public Criteria andTpidEqualTo(Integer value) {
            addCriterion("tpid =", value, "tpid");
            return (Criteria) this;
        }

        public Criteria andTpidNotEqualTo(Integer value) {
            addCriterion("tpid <>", value, "tpid");
            return (Criteria) this;
        }

        public Criteria andTpidGreaterThan(Integer value) {
            addCriterion("tpid >", value, "tpid");
            return (Criteria) this;
        }

        public Criteria andTpidGreaterThanOrEqualTo(Integer value) {
            addCriterion("tpid >=", value, "tpid");
            return (Criteria) this;
        }

        public Criteria andTpidLessThan(Integer value) {
            addCriterion("tpid <", value, "tpid");
            return (Criteria) this;
        }

        public Criteria andTpidLessThanOrEqualTo(Integer value) {
            addCriterion("tpid <=", value, "tpid");
            return (Criteria) this;
        }

        public Criteria andTpidIn(List<Integer> values) {
            addCriterion("tpid in", values, "tpid");
            return (Criteria) this;
        }

        public Criteria andTpidNotIn(List<Integer> values) {
            addCriterion("tpid not in", values, "tpid");
            return (Criteria) this;
        }

        public Criteria andTpidBetween(Integer value1, Integer value2) {
            addCriterion("tpid between", value1, value2, "tpid");
            return (Criteria) this;
        }

        public Criteria andTpidNotBetween(Integer value1, Integer value2) {
            addCriterion("tpid not between", value1, value2, "tpid");
            return (Criteria) this;
        }

        public Criteria andHeadidIsNull() {
            addCriterion("headid is null");
            return (Criteria) this;
        }

        public Criteria andHeadidIsNotNull() {
            addCriterion("headid is not null");
            return (Criteria) this;
        }

        public Criteria andHeadidEqualTo(Integer value) {
            addCriterion("headid =", value, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidNotEqualTo(Integer value) {
            addCriterion("headid <>", value, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidGreaterThan(Integer value) {
            addCriterion("headid >", value, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidGreaterThanOrEqualTo(Integer value) {
            addCriterion("headid >=", value, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidLessThan(Integer value) {
            addCriterion("headid <", value, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidLessThanOrEqualTo(Integer value) {
            addCriterion("headid <=", value, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidIn(List<Integer> values) {
            addCriterion("headid in", values, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidNotIn(List<Integer> values) {
            addCriterion("headid not in", values, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidBetween(Integer value1, Integer value2) {
            addCriterion("headid between", value1, value2, "headid");
            return (Criteria) this;
        }

        public Criteria andHeadidNotBetween(Integer value1, Integer value2) {
            addCriterion("headid not between", value1, value2, "headid");
            return (Criteria) this;
        }

        public Criteria andTpinfoIsNull() {
            addCriterion("tpinfo is null");
            return (Criteria) this;
        }

        public Criteria andTpinfoIsNotNull() {
            addCriterion("tpinfo is not null");
            return (Criteria) this;
        }

        public Criteria andTpinfoEqualTo(String value) {
            addCriterion("tpinfo =", value, "tpinfo");
            return (Criteria) this;
        }

        public Criteria andTpinfoNotEqualTo(String value) {
            addCriterion("tpinfo <>", value, "tpinfo");
            return (Criteria) this;
        }

        public Criteria andTpinfoGreaterThan(String value) {
            addCriterion("tpinfo >", value, "tpinfo");
            return (Criteria) this;
        }

        public Criteria andTpinfoGreaterThanOrEqualTo(String value) {
            addCriterion("tpinfo >=", value, "tpinfo");
            return (Criteria) this;
        }

        public Criteria andTpinfoLessThan(String value) {
            addCriterion("tpinfo <", value, "tpinfo");
            return (Criteria) this;
        }

        public Criteria andTpinfoLessThanOrEqualTo(String value) {
            addCriterion("tpinfo <=", value, "tpinfo");
            return (Criteria) this;
        }

        public Criteria andTpinfoLike(String value) {
            addCriterion("tpinfo like", value, "tpinfo");
            return (Criteria) this;
        }

        public Criteria andTpinfoNotLike(String value) {
            addCriterion("tpinfo not like", value, "tpinfo");
            return (Criteria) this;
        }

        public Criteria andTpinfoIn(List<String> values) {
            addCriterion("tpinfo in", values, "tpinfo");
            return (Criteria) this;
        }

        public Criteria andTpinfoNotIn(List<String> values) {
            addCriterion("tpinfo not in", values, "tpinfo");
            return (Criteria) this;
        }

        public Criteria andTpinfoBetween(String value1, String value2) {
            addCriterion("tpinfo between", value1, value2, "tpinfo");
            return (Criteria) this;
        }

        public Criteria andTpinfoNotBetween(String value1, String value2) {
            addCriterion("tpinfo not between", value1, value2, "tpinfo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table headtpinfo
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}