package cn.edu.hbpu.trip.pojo;

public class Headtpinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headtpinfo.tpid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer tpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headtpinfo.headid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer headid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column headtpinfo.tpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String tpinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headtpinfo.tpid
     *
     * @return the value of headtpinfo.tpid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getTpid() {
        return tpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headtpinfo.tpid
     *
     * @param tpid the value for headtpinfo.tpid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setTpid(Integer tpid) {
        this.tpid = tpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headtpinfo.headid
     *
     * @return the value of headtpinfo.headid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getHeadid() {
        return headid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headtpinfo.headid
     *
     * @param headid the value for headtpinfo.headid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setHeadid(Integer headid) {
        this.headid = headid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column headtpinfo.tpinfo
     *
     * @return the value of headtpinfo.tpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getTpinfo() {
        return tpinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column headtpinfo.tpinfo
     *
     * @param tpinfo the value for headtpinfo.tpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setTpinfo(String tpinfo) {
        this.tpinfo = tpinfo == null ? null : tpinfo.trim();
    }
}