package cn.edu.hbpu.trip.pojo;

public class Head {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column head.headid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer headid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column head.them
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String them;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column head.headpic
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String headpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column head.difid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer difid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column head.swappic
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String swappic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column head.headid
     *
     * @return the value of head.headid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getHeadid() {
        return headid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column head.headid
     *
     * @param headid the value for head.headid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setHeadid(Integer headid) {
        this.headid = headid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column head.them
     *
     * @return the value of head.them
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getThem() {
        return them;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column head.them
     *
     * @param them the value for head.them
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setThem(String them) {
        this.them = them == null ? null : them.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column head.headpic
     *
     * @return the value of head.headpic
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getHeadpic() {
        return headpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column head.headpic
     *
     * @param headpic the value for head.headpic
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setHeadpic(String headpic) {
        this.headpic = headpic == null ? null : headpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column head.difid
     *
     * @return the value of head.difid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getDifid() {
        return difid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column head.difid
     *
     * @param difid the value for head.difid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setDifid(Integer difid) {
        this.difid = difid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column head.swappic
     *
     * @return the value of head.swappic
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getSwappic() {
        return swappic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column head.swappic
     *
     * @param swappic the value for head.swappic
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setSwappic(String swappic) {
        this.swappic = swappic == null ? null : swappic.trim();
    }
}