package cn.edu.hbpu.trip.pojo;

public class Jdinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdinfo.jdid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer jdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdinfo.headid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer headid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdinfo.dengji
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer dengji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdinfo.jdprice
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer jdprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdinfo.jdctx
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String jdctx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdinfo.jdid
     *
     * @return the value of jdinfo.jdid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getJdid() {
        return jdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdinfo.jdid
     *
     * @param jdid the value for jdinfo.jdid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setJdid(Integer jdid) {
        this.jdid = jdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdinfo.headid
     *
     * @return the value of jdinfo.headid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getHeadid() {
        return headid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdinfo.headid
     *
     * @param headid the value for jdinfo.headid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setHeadid(Integer headid) {
        this.headid = headid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdinfo.dengji
     *
     * @return the value of jdinfo.dengji
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getDengji() {
        return dengji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdinfo.dengji
     *
     * @param dengji the value for jdinfo.dengji
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setDengji(Integer dengji) {
        this.dengji = dengji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdinfo.jdprice
     *
     * @return the value of jdinfo.jdprice
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getJdprice() {
        return jdprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdinfo.jdprice
     *
     * @param jdprice the value for jdinfo.jdprice
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setJdprice(Integer jdprice) {
        this.jdprice = jdprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdinfo.jdctx
     *
     * @return the value of jdinfo.jdctx
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getJdctx() {
        return jdctx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdinfo.jdctx
     *
     * @param jdctx the value for jdinfo.jdctx
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setJdctx(String jdctx) {
        this.jdctx = jdctx == null ? null : jdctx.trim();
    }
}