package cn.edu.hbpu.trip.pojo;

import java.util.Date;

public class Secondcontentinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondcontentinfo.secondctxid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer secondctxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondcontentinfo.contentid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer contentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondcontentinfo.uid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondcontentinfo.forid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer forid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondcontentinfo.secondtime
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Date secondtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column secondcontentinfo.secondctx
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String secondctx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondcontentinfo.secondctxid
     *
     * @return the value of secondcontentinfo.secondctxid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getSecondctxid() {
        return secondctxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondcontentinfo.secondctxid
     *
     * @param secondctxid the value for secondcontentinfo.secondctxid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setSecondctxid(Integer secondctxid) {
        this.secondctxid = secondctxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondcontentinfo.contentid
     *
     * @return the value of secondcontentinfo.contentid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getContentid() {
        return contentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondcontentinfo.contentid
     *
     * @param contentid the value for secondcontentinfo.contentid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setContentid(Integer contentid) {
        this.contentid = contentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondcontentinfo.uid
     *
     * @return the value of secondcontentinfo.uid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondcontentinfo.uid
     *
     * @param uid the value for secondcontentinfo.uid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondcontentinfo.forid
     *
     * @return the value of secondcontentinfo.forid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getForid() {
        return forid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondcontentinfo.forid
     *
     * @param forid the value for secondcontentinfo.forid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setForid(Integer forid) {
        this.forid = forid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondcontentinfo.secondtime
     *
     * @return the value of secondcontentinfo.secondtime
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Date getSecondtime() {
        return secondtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondcontentinfo.secondtime
     *
     * @param secondtime the value for secondcontentinfo.secondtime
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setSecondtime(Date secondtime) {
        this.secondtime = secondtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column secondcontentinfo.secondctx
     *
     * @return the value of secondcontentinfo.secondctx
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getSecondctx() {
        return secondctx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column secondcontentinfo.secondctx
     *
     * @param secondctx the value for secondcontentinfo.secondctx
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setSecondctx(String secondctx) {
        this.secondctx = secondctx == null ? null : secondctx.trim();
    }
}