package cn.edu.hbpu.trip.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SecondcontentinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public SecondcontentinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSecondctxidIsNull() {
            addCriterion("secondctxid is null");
            return (Criteria) this;
        }

        public Criteria andSecondctxidIsNotNull() {
            addCriterion("secondctxid is not null");
            return (Criteria) this;
        }

        public Criteria andSecondctxidEqualTo(Integer value) {
            addCriterion("secondctxid =", value, "secondctxid");
            return (Criteria) this;
        }

        public Criteria andSecondctxidNotEqualTo(Integer value) {
            addCriterion("secondctxid <>", value, "secondctxid");
            return (Criteria) this;
        }

        public Criteria andSecondctxidGreaterThan(Integer value) {
            addCriterion("secondctxid >", value, "secondctxid");
            return (Criteria) this;
        }

        public Criteria andSecondctxidGreaterThanOrEqualTo(Integer value) {
            addCriterion("secondctxid >=", value, "secondctxid");
            return (Criteria) this;
        }

        public Criteria andSecondctxidLessThan(Integer value) {
            addCriterion("secondctxid <", value, "secondctxid");
            return (Criteria) this;
        }

        public Criteria andSecondctxidLessThanOrEqualTo(Integer value) {
            addCriterion("secondctxid <=", value, "secondctxid");
            return (Criteria) this;
        }

        public Criteria andSecondctxidIn(List<Integer> values) {
            addCriterion("secondctxid in", values, "secondctxid");
            return (Criteria) this;
        }

        public Criteria andSecondctxidNotIn(List<Integer> values) {
            addCriterion("secondctxid not in", values, "secondctxid");
            return (Criteria) this;
        }

        public Criteria andSecondctxidBetween(Integer value1, Integer value2) {
            addCriterion("secondctxid between", value1, value2, "secondctxid");
            return (Criteria) this;
        }

        public Criteria andSecondctxidNotBetween(Integer value1, Integer value2) {
            addCriterion("secondctxid not between", value1, value2, "secondctxid");
            return (Criteria) this;
        }

        public Criteria andContentidIsNull() {
            addCriterion("contentid is null");
            return (Criteria) this;
        }

        public Criteria andContentidIsNotNull() {
            addCriterion("contentid is not null");
            return (Criteria) this;
        }

        public Criteria andContentidEqualTo(Integer value) {
            addCriterion("contentid =", value, "contentid");
            return (Criteria) this;
        }

        public Criteria andContentidNotEqualTo(Integer value) {
            addCriterion("contentid <>", value, "contentid");
            return (Criteria) this;
        }

        public Criteria andContentidGreaterThan(Integer value) {
            addCriterion("contentid >", value, "contentid");
            return (Criteria) this;
        }

        public Criteria andContentidGreaterThanOrEqualTo(Integer value) {
            addCriterion("contentid >=", value, "contentid");
            return (Criteria) this;
        }

        public Criteria andContentidLessThan(Integer value) {
            addCriterion("contentid <", value, "contentid");
            return (Criteria) this;
        }

        public Criteria andContentidLessThanOrEqualTo(Integer value) {
            addCriterion("contentid <=", value, "contentid");
            return (Criteria) this;
        }

        public Criteria andContentidIn(List<Integer> values) {
            addCriterion("contentid in", values, "contentid");
            return (Criteria) this;
        }

        public Criteria andContentidNotIn(List<Integer> values) {
            addCriterion("contentid not in", values, "contentid");
            return (Criteria) this;
        }

        public Criteria andContentidBetween(Integer value1, Integer value2) {
            addCriterion("contentid between", value1, value2, "contentid");
            return (Criteria) this;
        }

        public Criteria andContentidNotBetween(Integer value1, Integer value2) {
            addCriterion("contentid not between", value1, value2, "contentid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andForidIsNull() {
            addCriterion("forid is null");
            return (Criteria) this;
        }

        public Criteria andForidIsNotNull() {
            addCriterion("forid is not null");
            return (Criteria) this;
        }

        public Criteria andForidEqualTo(Integer value) {
            addCriterion("forid =", value, "forid");
            return (Criteria) this;
        }

        public Criteria andForidNotEqualTo(Integer value) {
            addCriterion("forid <>", value, "forid");
            return (Criteria) this;
        }

        public Criteria andForidGreaterThan(Integer value) {
            addCriterion("forid >", value, "forid");
            return (Criteria) this;
        }

        public Criteria andForidGreaterThanOrEqualTo(Integer value) {
            addCriterion("forid >=", value, "forid");
            return (Criteria) this;
        }

        public Criteria andForidLessThan(Integer value) {
            addCriterion("forid <", value, "forid");
            return (Criteria) this;
        }

        public Criteria andForidLessThanOrEqualTo(Integer value) {
            addCriterion("forid <=", value, "forid");
            return (Criteria) this;
        }

        public Criteria andForidIn(List<Integer> values) {
            addCriterion("forid in", values, "forid");
            return (Criteria) this;
        }

        public Criteria andForidNotIn(List<Integer> values) {
            addCriterion("forid not in", values, "forid");
            return (Criteria) this;
        }

        public Criteria andForidBetween(Integer value1, Integer value2) {
            addCriterion("forid between", value1, value2, "forid");
            return (Criteria) this;
        }

        public Criteria andForidNotBetween(Integer value1, Integer value2) {
            addCriterion("forid not between", value1, value2, "forid");
            return (Criteria) this;
        }

        public Criteria andSecondtimeIsNull() {
            addCriterion("secondtime is null");
            return (Criteria) this;
        }

        public Criteria andSecondtimeIsNotNull() {
            addCriterion("secondtime is not null");
            return (Criteria) this;
        }

        public Criteria andSecondtimeEqualTo(Date value) {
            addCriterion("secondtime =", value, "secondtime");
            return (Criteria) this;
        }

        public Criteria andSecondtimeNotEqualTo(Date value) {
            addCriterion("secondtime <>", value, "secondtime");
            return (Criteria) this;
        }

        public Criteria andSecondtimeGreaterThan(Date value) {
            addCriterion("secondtime >", value, "secondtime");
            return (Criteria) this;
        }

        public Criteria andSecondtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("secondtime >=", value, "secondtime");
            return (Criteria) this;
        }

        public Criteria andSecondtimeLessThan(Date value) {
            addCriterion("secondtime <", value, "secondtime");
            return (Criteria) this;
        }

        public Criteria andSecondtimeLessThanOrEqualTo(Date value) {
            addCriterion("secondtime <=", value, "secondtime");
            return (Criteria) this;
        }

        public Criteria andSecondtimeIn(List<Date> values) {
            addCriterion("secondtime in", values, "secondtime");
            return (Criteria) this;
        }

        public Criteria andSecondtimeNotIn(List<Date> values) {
            addCriterion("secondtime not in", values, "secondtime");
            return (Criteria) this;
        }

        public Criteria andSecondtimeBetween(Date value1, Date value2) {
            addCriterion("secondtime between", value1, value2, "secondtime");
            return (Criteria) this;
        }

        public Criteria andSecondtimeNotBetween(Date value1, Date value2) {
            addCriterion("secondtime not between", value1, value2, "secondtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table secondcontentinfo
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table secondcontentinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}