package cn.edu.hbpu.trip.pojo;

import java.util.List;

public class Shoppinginfo {
    private Goodsinfo goodsinfo;
    private String usertel;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppinginfo.shoppingid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer shoppingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppinginfo.uid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppinginfo.goodsid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppinginfo.personnum
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer personnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppinginfo.roomnum
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer roomnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppinginfo.startadd
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String startadd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppinginfo.maintel
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String maintel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppinginfo.bxnum
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer bxnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppinginfo.jdid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer jdid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppinginfo.shoppingid
     *
     * @return the value of shoppinginfo.shoppingid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getShoppingid() {
        return shoppingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppinginfo.shoppingid
     *
     * @param shoppingid the value for shoppinginfo.shoppingid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setShoppingid(Integer shoppingid) {
        this.shoppingid = shoppingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppinginfo.uid
     *
     * @return the value of shoppinginfo.uid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppinginfo.uid
     *
     * @param uid the value for shoppinginfo.uid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppinginfo.goodsid
     *
     * @return the value of shoppinginfo.goodsid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppinginfo.goodsid
     *
     * @param goodsid the value for shoppinginfo.goodsid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppinginfo.personnum
     *
     * @return the value of shoppinginfo.personnum
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getPersonnum() {
        return personnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppinginfo.personnum
     *
     * @param personnum the value for shoppinginfo.personnum
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setPersonnum(Integer personnum) {
        this.personnum = personnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppinginfo.roomnum
     *
     * @return the value of shoppinginfo.roomnum
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getRoomnum() {
        return roomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppinginfo.roomnum
     *
     * @param roomnum the value for shoppinginfo.roomnum
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setRoomnum(Integer roomnum) {
        this.roomnum = roomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppinginfo.startadd
     *
     * @return the value of shoppinginfo.startadd
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getStartadd() {
        return startadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppinginfo.startadd
     *
     * @param startadd the value for shoppinginfo.startadd
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setStartadd(String startadd) {
        this.startadd = startadd == null ? null : startadd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppinginfo.maintel
     *
     * @return the value of shoppinginfo.maintel
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getMaintel() {
        return maintel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppinginfo.maintel
     *
     * @param maintel the value for shoppinginfo.maintel
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setMaintel(String maintel) {
        this.maintel = maintel == null ? null : maintel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppinginfo.bxnum
     *
     * @return the value of shoppinginfo.bxnum
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getBxnum() {
        return bxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppinginfo.bxnum
     *
     * @param bxnum the value for shoppinginfo.bxnum
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setBxnum(Integer bxnum) {
        this.bxnum = bxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppinginfo.jdid
     *
     * @return the value of shoppinginfo.jdid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getJdid() {
        return jdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppinginfo.jdid
     *
     * @param jdid the value for shoppinginfo.jdid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setJdid(Integer jdid) {
        this.jdid = jdid;
    }

    public String getUsertel() {
        return usertel;
    }

    public void setUsertel(String usertel) {
        this.usertel = usertel;
    }


    public Goodsinfo getGoodsinfo() {
        return goodsinfo;
    }

    public void setGoodsinfo(Goodsinfo goodsinfo) {
        this.goodsinfo = goodsinfo;
    }
}