package cn.edu.hbpu.trip.pojo;

import java.util.List;

public class Stateinfo {
    private List<Goodsinfo> goodsinfos;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stateinfo.productid
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stateinfo.goodsid
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stateinfo.stateid
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    private Integer stateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stateinfo.uid
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stateinfo.productid
     *
     * @return the value of stateinfo.productid
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stateinfo.productid
     *
     * @param productid the value for stateinfo.productid
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stateinfo.goodsid
     *
     * @return the value of stateinfo.goodsid
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stateinfo.goodsid
     *
     * @param goodsid the value for stateinfo.goodsid
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stateinfo.stateid
     *
     * @return the value of stateinfo.stateid
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    public Integer getStateid() {
        return stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stateinfo.stateid
     *
     * @param stateid the value for stateinfo.stateid
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    public void setStateid(Integer stateid) {
        this.stateid = stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stateinfo.uid
     *
     * @return the value of stateinfo.uid
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stateinfo.uid
     *
     * @param uid the value for stateinfo.uid
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public List<Goodsinfo> getGoodsinfos() {
        return goodsinfos;
    }

    public void setGoodsinfos(List<Goodsinfo> goodsinfos) {
        this.goodsinfos = goodsinfos;
    }
}