package cn.edu.hbpu.trip.pojo;

public class Swap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap.picid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer picid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap.swappic
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private String swappic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swap.difid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    private Integer difid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap.picid
     *
     * @return the value of swap.picid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getPicid() {
        return picid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap.picid
     *
     * @param picid the value for swap.picid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setPicid(Integer picid) {
        this.picid = picid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap.swappic
     *
     * @return the value of swap.swappic
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public String getSwappic() {
        return swappic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap.swappic
     *
     * @param swappic the value for swap.swappic
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setSwappic(String swappic) {
        this.swappic = swappic == null ? null : swappic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column swap.difid
     *
     * @return the value of swap.difid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public Integer getDifid() {
        return difid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column swap.difid
     *
     * @param difid the value for swap.difid
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    public void setDifid(Integer difid) {
        this.difid = difid;
    }
}