package cn.edu.hbpu.trip.mapper;

import cn.edu.hbpu.trip.pojo.Glinfo;
import cn.edu.hbpu.trip.pojo.GlinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GlinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int countByExample(GlinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int deleteByExample(GlinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer glid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int insert(Glinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int insertSelective(Glinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    List<Glinfo> selectByExampleWithBLOBs(GlinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    List<Glinfo> selectByExample(GlinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    Glinfo selectByPrimaryKey(Integer glid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Glinfo record, @Param("example") GlinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Glinfo record, @Param("example") GlinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Glinfo record, @Param("example") GlinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Glinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByPrimaryKeyWithBLOBs(Glinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByPrimaryKey(Glinfo record);
}