package cn.edu.hbpu.trip.mapper;

import cn.edu.hbpu.trip.pojo.Head;
import cn.edu.hbpu.trip.pojo.HeadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface HeadMapper {

    @Select("select * from head")
    public List<Head> getHead();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int countByExample(HeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int deleteByExample(HeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer headid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int insert(Head record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int insertSelective(Head record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    List<Head> selectByExample(HeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    Head selectByPrimaryKey(Integer headid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Head record, @Param("example") HeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Head record, @Param("example") HeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Head record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table head
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByPrimaryKey(Head record);
}