package cn.edu.hbpu.trip.mapper;

import cn.edu.hbpu.trip.pojo.Headtpinfo;
import cn.edu.hbpu.trip.pojo.HeadtpinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HeadtpinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int countByExample(HeadtpinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int deleteByExample(HeadtpinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer tpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int insert(Headtpinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int insertSelective(Headtpinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    List<Headtpinfo> selectByExample(HeadtpinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    Headtpinfo selectByPrimaryKey(Integer tpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Headtpinfo record, @Param("example") HeadtpinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Headtpinfo record, @Param("example") HeadtpinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Headtpinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table headtpinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByPrimaryKey(Headtpinfo record);
}