package cn.edu.hbpu.trip.mapper;

import cn.edu.hbpu.trip.pojo.Jdinfo;
import cn.edu.hbpu.trip.pojo.JdinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JdinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int countByExample(JdinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int deleteByExample(JdinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int insert(Jdinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int insertSelective(Jdinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    List<Jdinfo> selectByExampleWithBLOBs(JdinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    List<Jdinfo> selectByExample(JdinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Jdinfo record, @Param("example") JdinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Jdinfo record, @Param("example") JdinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jdinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Jdinfo record, @Param("example") JdinfoExample example);
}