package cn.edu.hbpu.trip.mapper;

import cn.edu.hbpu.trip.pojo.Picinfo;
import cn.edu.hbpu.trip.pojo.PicinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface PicinfoMapper {
    @Select("select * from picinfo where goodsid=#{goodsid}")
    List<Picinfo> getPicInfo(int goodsid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int countByExample(PicinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int deleteByExample(PicinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer picid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int insert(Picinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int insertSelective(Picinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    List<Picinfo> selectByExample(PicinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    Picinfo selectByPrimaryKey(Integer picid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Picinfo record, @Param("example") PicinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Picinfo record, @Param("example") PicinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Picinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picinfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByPrimaryKey(Picinfo record);
}