package cn.edu.hbpu.trip.mapper;

import cn.edu.hbpu.trip.pojo.Goodsinfo;
import cn.edu.hbpu.trip.pojo.Shoppinginfo;
import cn.edu.hbpu.trip.pojo.ShoppinginfoExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

public interface ShoppinginfoMapper {
    //查询user是否有该商品
    @Select("select * from shoppinginfo where goodsid=#{goodsid} and uid=#{uid}")
    Shoppinginfo isThisGoods(@Param("goodsid") int goodsid,@Param("uid") int uid);
    //查询某一条信息的数量
    @Select("select personnum from shoppinginfo where goodsid=#{goodsid} and uid=#{uid}")
    Integer goodsNum(@Param("goodsid") int goodsid,@Param("uid") int uid);
    //查询user的购物车商品
    @Select("select * from shoppinginfo where uid=#{uid}")
    @Results({
            @Result(property = "goodsid", column = "goodsid"),
            @Result(property = "goodsinfo", column = "goodsid",
                    one = @One(select = "cn.edu.hbpu.trip.mapper.GoodsinfoMapper.getShoppingGoods"))
    })
    List<Shoppinginfo> getShoppingInfo(int uid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppinginfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int countByExample(ShoppinginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppinginfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int deleteByExample(ShoppinginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppinginfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer shoppingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppinginfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int insert(Shoppinginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppinginfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int insertSelective(Shoppinginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppinginfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    List<Shoppinginfo> selectByExample(ShoppinginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppinginfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    Shoppinginfo selectByPrimaryKey(Integer shoppingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppinginfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Shoppinginfo record, @Param("example") ShoppinginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppinginfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Shoppinginfo record, @Param("example") ShoppinginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppinginfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Shoppinginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppinginfo
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByPrimaryKey(Shoppinginfo record);
}