package cn.edu.hbpu.trip.mapper;

import cn.edu.hbpu.trip.pojo.Stateinfo;
import cn.edu.hbpu.trip.pojo.StateinfoExample;
import java.util.List;

import org.apache.ibatis.annotations.*;

public interface StateinfoMapper {
    //查询订单的状态
    @Select("select * from stateinfo where uid=#{uid} and stateid=#{stateid}")
    @Results({
            @Result(property = "goodsid", column = "goodsid"),
            @Result(property = "goodsinfos", column = "goodsid",
                    many = @Many(select = "cn.edu.hbpu.trip.mapper.GoodsinfoMapper.getGoods"))
    })
    List<Stateinfo> getStateGoods(@Param("uid") int uid,@Param("stateid") int stateid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stateinfo
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    int countByExample(StateinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stateinfo
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    int deleteByExample(StateinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stateinfo
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer productid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stateinfo
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    int insert(Stateinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stateinfo
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    int insertSelective(Stateinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stateinfo
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    List<Stateinfo> selectByExample(StateinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stateinfo
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    Stateinfo selectByPrimaryKey(Integer productid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stateinfo
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Stateinfo record, @Param("example") StateinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stateinfo
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Stateinfo record, @Param("example") StateinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stateinfo
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Stateinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stateinfo
     *
     * @mbggenerated Wed Dec 22 12:34:47 GMT+08:00 2021
     */
    int updateByPrimaryKey(Stateinfo record);
}