package cn.edu.hbpu.trip.mapper;

import cn.edu.hbpu.trip.pojo.Swap;
import cn.edu.hbpu.trip.pojo.SwapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SwapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int countByExample(SwapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int deleteByExample(SwapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer picid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int insert(Swap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int insertSelective(Swap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    List<Swap> selectByExample(SwapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    Swap selectByPrimaryKey(Integer picid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") Swap record, @Param("example") SwapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByExample(@Param("record") Swap record, @Param("example") SwapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Swap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swap
     *
     * @mbggenerated Sun Dec 19 11:02:10 GMT+08:00 2021
     */
    int updateByPrimaryKey(Swap record);
}