package cn.edu.hbpu.trip.mapper;

import cn.edu.hbpu.trip.pojo.User;
import cn.edu.hbpu.trip.pojo.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface UserMapper {
    //查询用户信息
    @Select("select username,headpic,uid from user where uid=#{uid}")
    User getUserinfo(int uid);

    //查询评论区的留言信息
    @Select("select uid,username,headpic,usertel from user where usertel=#{usertel} and password=#{password}")
    User canLogin(@Param("usertel") String usertel,@Param("password") String password);
    //通过电话号码查询uid
    @Select("select uid from user where usertel=#{usertel}")
    User getUserUid(String usertel);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 20 20:18:32 GMT+08:00 2021
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 20 20:18:32 GMT+08:00 2021
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 20 20:18:32 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 20 20:18:32 GMT+08:00 2021
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 20 20:18:32 GMT+08:00 2021
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 20 20:18:32 GMT+08:00 2021
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 20 20:18:32 GMT+08:00 2021
     */
    User selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 20 20:18:32 GMT+08:00 2021
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 20 20:18:32 GMT+08:00 2021
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 20 20:18:32 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 20 20:18:32 GMT+08:00 2021
     */
    int updateByPrimaryKey(User record);
}